### PR TITLE
Add Pratheek to people page

### PR DESCRIPTION
**Pull request by pratheekkerthivenkata**
Please approve my pull request.

Thanks,
Pratheek

### CODE REVIEW

**Comment by alecive** [comment]
@pratheekkerthivenkata as you can see here: https://deploy-preview-220--cranky-jackson-a3e285.netlify.app/people , the PR breaks the website rendering. Please fix.

**Comment by pratheekkerthivenkata** [comment]
Hello,

Apologies for the error. I've updated the file, please review and merge the pull request.

**Review by pratheekkerthivenkata — COMMENTED** [review]
Updated people.yml

**Comment by alecive** [comment]
Great! Thanks.

**Review by alecive — APPROVED** [review]

**Pull request merged**
