### PR TITLE
Put on zoom instead of classroom (Fixes #96)

### LINKED ISSUE #96: Change lab meetings times on the website
As per title

### PR DESCRIPTION
**Pull request by KedarMore**

### CODE REVIEW

**Comment by alecive** [comment]
Have you checked that the text is rendered properly on the generated website? See netlify above

**Comment by peasant98** [comment]
"we will be holding group meetings in On Zoom" -> "we will be holding group meetings on Zoom"?

**Comment by joewie** [comment]
@alecive Thoughts?

**Comment by alecive** [comment]
> "we will be holding group meetings in On Zoom" -> "we will be holding group meetings on Zoom"?

That's what I mean @peasant98 @joewie

**Pull request merged**
