### PR TITLE
Add Stephane to people page

### PR DESCRIPTION
**Pull request by StephAO**
Finally adding myself. My personal github page will go in later

### CODE REVIEW

**Comment by watakandai** [comment]
you forgot to add your photo.

**Comment by StephAO** [comment]
> you forgot to add your photo.
I see the picture in the commit on my end. I accidentally had the wrong picture name (stephane.jpg instead of stephane.png), but I've fixed that now

**Comment by watakandai** [comment]
oh my bad

**Comment by watakandai** [comment]
yeah finally you appeared on the website.
https://deploy-preview-111--cranky-jackson-a3e285.netlify.app/people.html

**Review by watakandai — APPROVED** [review]

**Pull request merged**
