### PR TITLE
Added Shamal profile

### PR DESCRIPTION
**Pull request by idrissdjio**

### CODE REVIEW

**Comment by alecive** [comment]
Why is this committed by @idrissdjio if it's about Shamal's stuff?

**Review by alecive — CHANGES_REQUESTED** [review]
The picture is not a square picture. I mean, it's square, but it's a rectangle. Please fix

**Comment by idrissdjio** [comment]
Shamal was having issue pushing the code, so I did the push request on his
behalf.

-----
Idriss Djiofack
Graduate Researcher @ HIRO Lab
French Teaching Assistant, *Department of French and Italian  *
Computer Science Graduate Student @ *University of Colorado Boulder*
Website: https://idrissdjio.github.io/
Sign Up for Office Hours <https://calendly.com/iddj6806/30min>

**Comment by idrissdjio** [comment]
Ok I will ask him to provide me with the correct image size.

-----
Idriss Djiofack
Graduate Researcher @ HIRO Lab
French Teaching Assistant, *Department of French and Italian  *
Computer Science Graduate Student @ *University of Colorado Boulder*
Website: https://idrissdjio.github.io/
Sign Up for Office Hours <https://calendly.com/iddj6806/30min>

**Comment by idrissdjio** [comment]
> The picture is not a square picture. I mean, it's square, but it's a rectangle. Please fix

I just updated the codebase with the new picture. pushed the code to the add-shamal branch

**Review by alecive — APPROVED** [review]

**Pull request merged**
