### PR TITLE
my webpage -- finally

### PR DESCRIPTION
**Pull request by a-nooj**
#21

### CODE REVIEW

**Comment by alecive** [comment]
Woooooo I think I'm gonna cry 🤣 
Ok so while I think it's okay how you set it up, I feel like users should have a more streamlined UX to get to the interesting bits of your work and your projects. 

Currently, I have to do the following: 

1. click on the people page
2. click on your face
3. click on the very not visible link at the bottom of https://deploy-preview-65--cranky-jackson-a3e285.netlify.com/anuj.html
4. [first redirect]
5. understand that https://anuj.carrd.co/ is a landing page and that I have to click on the `information` icon
6. [second redirect]
7. reach a third website with all the links

Isn't it too much? 

Wouldn't be worth to duplicate some of the information (e.g. projects) on your webpage on the HIRO group personal link?

**Comment by a-nooj** [comment]
Hopefully, that fixes the issues we discussed.

Need to add a link to my personal page (anuj.carrd.co) under "Name>Email Address" on the picture hover screen...which I don't know how to do.

**Comment by alecive** [comment]
Ok as agreed, I look forward to seeing your profile pic a little bit lightened up :-)

**Comment by alecive** [comment]
> Need to add a link to my personal page (anuj.carrd.co) under "Name>Email Address" on the picture hover screen...which I don't know how to do.

I'll take care of it. Can you please open an issue so that I don't forget?

**Comment by a-nooj** [comment]
> I'll take care of it. Can you please open an issue so that I don't forget?

Done: #67

**Comment by alecive** [comment]
What a difference some photoshop editing makes! Thanks @a-nooj , I'll fix the issue at some point later on.

**Pull request merged**
