### PR TITLE
Added research section to home page and dedicated research tab

### PR DESCRIPTION
**Pull request by alecive**
Features: 

- added new research tab
- added new research subsection in the homepage that shows the research articles
- the research page shows the articles and an excerpt of the article itself. Required a couple fixes to the PRs to make it work but it's cool
- There is a feature image too (in the research page)
- I know, we can't test until one of the otehr PRs are merged
- Overall, I feel it's pretty cool

### CODE REVIEW

**Comment by joewie** [comment]
How do you make articles show up on the research page? I can only get mine to appear on the homepage.

**Comment by alecive** [comment]
@joewie I have just committed a major improvement. Now it should be working without you having to do much.

**Comment by joewie** [comment]
> @joewie I have just committed a major improvement. Now it should be working without you having to do much.

Looks great! Except the image links to the image instead of the page.

On the research article itself, images link to themselves too.

**Comment by alecive** [comment]
Sorry, say it again? I didn't get it

**Comment by alecive** [comment]
Also, @joewie please take a look at the parameters in the front matter I have added to anuj's page.

**Comment by joewie** [comment]
> Sorry, say it again? I didn't get it

Uh, hard to explain, I sent you a video.

**Comment by alecive** [comment]
A++

**Pull request merged**
