### PR TITLE
Fix personal pages

### PR DESCRIPTION
**Pull request by alecive**
As per title. Added automatic parsing of the data in the personal webpage and simultaneously removed that horrifying piece of code that was there earlier.

@joewie @calebescobedo before merging this, can you please have a look at this PR and see if the rendered personal page for the both of you works as expected? Thanks!

### CODE REVIEW

**Comment by joewie** [comment]
> removed that horrifying piece of code that was there earlier.

Oof.

**Comment by alecive** [comment]
It all seems good to me, but I'd like to have a backup opinion.

**Comment by joewie** [comment]
Was removing the publication year sub-headers an intentional decision?

**Comment by alecive** [comment]
> 
> 
> Was removing the publication year sub-headers an intentional decision?

Yes, I don't think it makes sense given that you have 2 publications.

**Pull request merged**
