### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by peasant98**
This PR fixes the readme, first by getting rid of the compressed logo.

### CODE REVIEW

**Comment by alecive** [comment]
I'm fine with the PNG file-- what I meant is that the logo should be imported in markdown format and not HTML. As in: 

long-logo-dark-text

And since we are here, just link to this file so as not to increase the amount of space in the repo. As in, copy paste the following:

`long-logo-dark-text`

**Comment by alecive** [comment]
I'm fine with the PNG file-- what I meant is that the logo should be imported in markdown format and not HTML. As in: 

long-logo-dark-text

And since we are here, just link to this file so as not to increase the amount of space in the repo. As in, copy paste the following:

`long-logo-dark-text`

**Comment by alecive** [comment]
Damn my internet dropped while I was commenting and I automatically accepted the PR!

**Comment by joewie** [comment]
> Damn my internet dropped while I was commenting and I automatically accepted the PR!

That wasn't you heh.

**Pull request merged**
