### PR TITLE
new member tutorial

### PR DESCRIPTION
**Pull request by a-nooj**
created PR to preview on netlify; not ready to merge

### CODE REVIEW

**Comment by a-nooj** [comment]
not ready to review yet. i'll ping Joewie when it is.

**Comment by alecive** [comment]
@a-nooj please also ping me when it's ready---it seems to be a big PR :-)

**Comment by alecive** [comment]
Is it ready to be reviewed? If so, do you mind giving me an overview of your changes?

**Comment by a-nooj** [comment]
Not quite, haven't worked on this in a while. Will push another commit and provide a list of changes by Wednesday.

**Comment by peasant98** [comment]
Hi, any updates on this @a-nooj? I can take it up if need be.

**Comment by alecive** [comment]
@a-nooj

**Pull request closed without merging**
