### PR TITLE
add jay

### PR DESCRIPTION
**Pull request by Jdvakil**

### CODE REVIEW

**Review by alecive — CHANGES_REQUESTED** [review]
Please upload a 400x400 square image. Thanks!

**Comment by Jdvakil** [comment]
> Please upload a 400x400 square image. Thanks!

Done!

**Comment by alecive** [comment]
It still is not a square picture:  W: 298px | H: 264px

**Comment by Jdvakil** [comment]
> It still is not a square picture: W: 298px | H: 264px

I missed it 😛, Just uploaded a better 400x400 image

**Review by alecive — APPROVED** [review]

**Pull request merged**
